# Generated by Django 5.2.1 on 2025-05-09 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitydate', models.DateField(verbose_name='Activity Date')),
                ('starttime', models.TimeField(verbose_name='Start Time')),
                ('endtime', models.TimeField(verbose_name='End Time')),
                ('activitytype', models.CharField(max_length=255, verbose_name='Activity Type')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Food Name')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand')),
                ('servingsize', models.FloatField(verbose_name='Serving Size')),
                ('servingunit', models.CharField(max_length=255, verbose_name='Serving Unit')),
                ('calories', models.FloatField(verbose_name='Calories')),
                ('protein', models.FloatField(verbose_name='Protein')),
                ('carbohydrates', models.FloatField(verbose_name='Carbohydrates')),
                ('fat', models.FloatField(verbose_name='Fat')),
                ('sodium', models.FloatField(verbose_name='Sodium')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealdate', models.DateField(verbose_name='Meal Date')),
                ('mealtime', models.TimeField(verbose_name='Meal Time')),
                ('mealtype', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=255, verbose_name='Meal Type')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goaltype', models.CharField(max_length=255, verbose_name='Goal Type')),
                ('goalvalue', models.FloatField(verbose_name='Goal Value')),
                ('startdate', models.DateField(verbose_name='Start Date')),
                ('enddate', models.DateField(verbose_name='End Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SonareSoma.food', verbose_name='Food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SonareSoma.meal', verbose_name='Meal')),
            ],
            options={
                'verbose_name': 'Meal Food Item',
                'verbose_name_plural': 'Meal Food Items',
                'unique_together': {('meal', 'food')},
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(related_name='meals', through='SonareSoma.MealFood', to='SonareSoma.food', verbose_name='Foods'),
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals', models.ManyToManyField(related_name='nutrition_plans', to='SonareSoma.meal', verbose_name='Meals')),
            ],
            options={
                'verbose_name': 'Nutrition Plan',
                'verbose_name_plural': 'Nutrition Plans',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession')),
                ('specialty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professional',
                'verbose_name_plural': 'Professionals',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='SonareSoma.professional', verbose_name='Professional')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.ManyToManyField(related_name='routines', to='SonareSoma.activity', verbose_name='Activities')),
            ],
            options={
                'verbose_name': 'Routine',
                'verbose_name_plural': 'Routines',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('dateofbirth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='SonareSoma.goal', verbose_name='Goal')),
                ('nutrition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='SonareSoma.nutrition', verbose_name='Nutrition')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_profiles', to='SonareSoma.professional', verbose_name='Professional')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='SonareSoma.routine', verbose_name='Routine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]

